<h1>Produtos</h1>

<h1><?php echo $acao; ?></h1>

<a href="<?php echo $this->url('application/default',
        array('controller'=>'produtos','action' => 'index')) ?>">Index</a>

<a href="<?php echo $this->url('application/default', 
        array('controller'=>'produtos','action' => 'add')) ?>">Add</a>

<a href="<?php echo $this->url('application/default', 
        array('controller'=>'produtos','action' => 'edit')) ?>">Edit</a>

<a href="<?php echo $this->url('application/default', 
        array('controller'=>'produtos','action' => 'delete')) ?>">Delete</a>
