<h1>Clientes</h1>

<h2><?php echo $acao; ?></h2>

<a href="<?php echo $this->url('application/default',
        array('controller'=>'clientes','action' => 'index')) ?>">Index</a>

<a href="<?php echo $this->url('application/default', 
        array('controller'=>'clientes','action' => 'add')) ?>">Add</a>

<a href="<?php echo $this->url('application/default', 
        array('controller'=>'clientes','action' => 'edit')) ?>">Edit</a>

<a href="<?php echo $this->url('application/default', 
        array('controller'=>'clientes','action' => 'delete')) ?>">Delete</a>
