<?php

$title = 'Nova origem';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('rota_padrao', array('controller'=>'origem','action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
