<?php
$title = 'Origens';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('rota_padrao', array('controller'=>'origem','action'=>'add'));?>">Nova origem</a>
</p>

<table class="table">
<tr>
    <th>Id</th>
    <th>Nome</th>
    <th>&nbsp;</th>
</tr>
<?php


foreach ($origens as $origem) : ?>
<tr>
    <td><?php echo $this->escapeHtml($origem->id);?></td>
    <td><?php echo $this->escapeHtml($origem->nome);?></td>
    <td>
        <a href="<?php echo $this->url('rota_padrao',
            array('controller'=>'origem','action'=>'edit', 'id' => $origem->id));?>">Alterar</a>
        <a href="<?php echo $this->url('rota_padrao',
            array('controller'=>'origem','action'=>'delete', 'id' => $origem->id));?>">Apagar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>